### ISSUE TITLE
Be explicit about what arguments accomplish

### ISSUE THREAD

**Issue by pletcher** [learn-co-curriculum/skills-based-js-intro-to-functions#1]
They're ways of changing the data that's available to a function.

**Comment by jmburges** [comment]
Also make them feel the pain. Something like.

Ok so we can make a method that greets Chuck:

```
function greetChuck() {
  console.log("Hi Chuck");
}
```

What if we want to greet Joe as well? Now we need two methods:

```
function greetChuck() {
  console.log("Hi Chuck");
}
function greetJoe() {
  console.log("Hi Joe");
}
```

Ok, let's greet Ann:

```
function greetChuck() {
  console.log("Hi Chuck");
}
function greetJoe() {
  console.log("Hi Joe");
}
function greetAnn() {
  console.log("Hi Ann");
}
```

This is getting a bit silly. It's obvious what is staying the same, and what is changing. Wouldn't it be better if we just had one general purpose function that would just "ask" the user for the name? That's where function arguments come in!
