### ISSUE TITLE
Console.Log + Return FUNCTIONS NOT Working as in the Lab

### ISSUE THREAD

**Issue by PhillipFine** [learn-co-curriculum/skills-based-js-intro-to-functions#17]
Functions with console.log and return are NOT working per the lesson.  
1st, lesson seems to be missing a comma.  Interpreter won't even take it without the comma after the return `  ` part.  Gives Syntax Error: Unexpected Idenftifier.
2nd - after inserting the comma, after the return `   ` part and before console.log, the interpreter accepts it, but calling the function gives ONLY the console.log string ?!?!  
3rd - trying to switch, putting the console.log 1st and then then the return, Following the lesson (no comma after console.log ('string') or WITH a comma after console.log('string'), all the same it responds Syntax error:  Unexpected token return.

I've checked my typing so many times over so much time, even overnight with fresh eyes, and I'm not seeing why the problem.  Screenprint is attached/uploaded.  Am having ZERO problems with functions with JUST console.log or JUST return-ing multiple arguments passed to it.  ZERO success with any function where they are joined.
![fx console log ret not working](https://cloud.githubusercontent.com/assets/24758145/21473441/6d8a4db0-cad9-11e6-8f5e-ec7b62a48541.png)

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 🙂
