### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by RuffianX** [learn-co-curriculum/skills-based-js-intro-to-functions#19]
"Note that `name` is only available in the body of the function. If we just type `name` in the console, we'll get an error because it's undefined!"

This is incorrect; `name` is a property of the window object (and is a string). So typing `name `- or `window.name` - into the console will return "" (an empty string).

**Comment by gj** [comment]
Hi @RuffianX !

You're correct, but, to clarify for anyone else happening upon this issue in the future, the `name` property of the `window` object has *nothing* to do with the `name` parameter in our `sayHelloTo()` function declaration.

Thanks for pointing this out!
