### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by annieeby** [learn-co-curriculum/skills-based-js-intro-to-functions#39]
Readme says: when we just call console.log("Hello", "Chuck!"), we instead see only Hello, Chuck!

(with a comma between Hello and Chuck)

But console.log("Hello", "Chuck!") yields Hello Chuck!

(without the comma between Hello and Chuck)

Really a minute and insignificant detail(!), but the differences in this paragraph are so subtle with regard to the commas and quotation marks that I suppose every detail matters in aiding understanding. In general, despite reading several times, I am finding the paragraph where the typo was found pretty confusing -- could possibly benefit from some clarifying/simplifying edits.

**Comment by rrcobb** [comment]
Closed by 13dca8e4e70abab85d81074093de1e2b2c74252b - definitely a confusing line to have a typo in, took me a minute or two just to figure out what what was going on.

Fixed the typo, but this whole example could probably be reworked.
