### ISSUE TITLE
Lesson on variables before this

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/skills-based-js-intro-to-functions#6]
Are we assuming that students will know what a variable is? We mention variables and show string interpolation here with variables here but that can be overwhelming. I know there's a lesson on variables in this lesson, but can we take the first section of that lesson and add it as a separate lesson before this one. For reference again, here's how it's covered in other tracks:

This is a lot of information at once; all really good info and well presented but I think we should add a lesson on variables before and in that lesson, we'll cover variables as well as introduce them to the string and number data type.

n Ruby- "Variables allow us to store information. We tell our computer to set aside some space to hold that information so we can retrieve it later. A variable is the location where the information resides, when we need it we know just where to look."

And how it's covered in Swift- "Variables are the fundamental building block of any program. A variable associates a name with a value. That value can be almost anything: a number, a string (or sequence of characters), or even an object (which you will learn about in a future lesson). For instance, the following is a variable declaration in Swift:

var favoriteCharacter = "Jon Snow"
In the above example, a variable is declared using the var keyword. The name of the variable is favoriteCharacter. This variable has the value "Jon Snow". "Jon Snow" is a string, or sequence of characters enclosed in double quotation marks.

You can refer to this variable using its name. While the variable's value is initially "Jon Snow", it can change over time. For example, you could change it to "Tyrion Lannister":"
## 

@jmburges

**Comment by pletcher** [comment]
There are no variables in this lesson.

I think there's confusion between a variable and an argument here, which I didn't anticipate.

This isn't really the place to cover variables, and variables in JavaScript are _very_ different than in Swift and Ruby.

What I can do is move the variables section up. I really didn't want to do this, as understanding variables in JavaScript _requires_ that one understands functions; but if it's going to be confusing to students, I guess that's what we do.

**Comment by AnnJohn** [comment]
The reason why I raised is because of this line here in the reading:

"What if we want to say something other than "Hello"? Well, we can move the greeting to a variable as well:"

If that's not intended to be a variable, then should be changed

**Comment by pletcher** [comment]
Ah, got it -- thanks. That was a typo -- my bad :(

**Comment by AnnJohn** [comment]
great!

**Comment by pletcher** [comment]
I also created this: https://github.com/learn-co-curriculum/javascript-intro-to-variable-assignment-and-declaration
