### ISSUE TITLE
Separate into different lessons? 

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/skills-based-js-intro-to-functions#7]
Not super high priority, but can we separate this so that 

1) Lesson on just functions
2) Lab on that 
3) Lesson on arguments (single and multiple and have this be clarified just a bit more with more examples)
4) Lab on arguments

Also should return values be introduced for the first time here? This seems important and here it feels sort of rushed and also at the very end of a lesson that already has a lot of info. 

@jmburges

**Comment by pletcher** [comment]
I'm curious to see how students do with this, actually. Is it okay if we icebox this one until after launch?

If students really struggle, let's split it up. But right now, the narrative is pretty tight (saying hello, etc. -- I just cribbed the example from Ruby (and from lots of intro courses, I think)) -- and, truthfully, I'm curious if students might be able to really hit the ground running with this stuff :)
